### ISSUE TITLE
Catalog schema

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/opendatasicilia.it#74]
Ciao @aborruso, ti allego sotto un paio di info sulla struttura yaml che ho abbozzato per il catalogo di ods. Sentiti liberissimo di apportare le tue modifiche! Nessuno meglio di te padroneggia questi metadati ;) 

---

## Idea base
- Il **catalogo** è un insieme di **artifact**;
- esistono 3 grandi tipologie di artifact:
  - **progetto** (`project`)
  - **dataset** (`dataset`)
  - **dataviz** (che a loro volta si dividono in):
    - `map`
    - `table`
    - `chart`
    - `dashboard`

Possono anche esistere tuttavia artifact di tipo `site` e `api` che non rientrano nelle categorie sopra citate.

## Bozza di schema del catalogo

Il catalogo è essenzialmente una lista di artifacts. Ogni artifact è codificato come un oggetto a cui possono essere attribuite le seguenti chiavi.

| **Chiave**                   | **Tipo**            | **Descrizione**                                                                                                                                                         | **Esempio**                                                                                                                                                      |
|------------------------------|---------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `name`                       | Testo semplice      | Identificatore univoco dell'artifact.                                                                                                                   | `project-emergenza-idrica`                                                                                                                                       |
| `title`                      | Testo semplice      | Titolo descrittivo dell'artifact.                                                                                                                         | `Emergenza idrica`                                                                                                                                               |
| `description`                | Testo semplice      | Descrizione testuale (anche molto approfondita) dell'artifact. Nel caso in cui si trattasse di un artifact di tipo `project`, potrebbe esserci del testo che spiega lo scopo del progetto. È incoraggiato l'uso della sintassi markdown.                                                                                     | `Emergenza idrica in Sicilia. Raccogliamo dati, dashboard e avvisi dei gestori idrici (...).`                                                                           |
| `type`                       | Testo semplice      | Specifica la tipologia dell'artifact. Può assumere i seguenti valori: `project`, `dataset`, `site`, `api`, `chart`, `map`, `table`, `dashboard`.                                                                                             | `project`                                                                                                                                           |
| `url`                        | URL       | URL di collegamento alla risorsa online.                                                                                                                                 | `https://opendatasicilia.github.io/emergenza-idrica-sicilia/`                                                                                                     |
| `iframe`                     | Testo semplice      | Codice HTML per incorporare un iframe (es. mappe o dashboard)                                                                                                            | `<iframe width="100%" height="850px" src="..."></iframe>`                                                                                                        |
| `resource`                   | Lista di un oggetto              | Questa chiave fornisce delle specifiche relative alla chiave `url`. In particolare, se l'url rimanda a un datapackage frictionless, la chiave `resource` è utile per individuare la posizione del datapackage (è posizionato nella root del repo o in sottocartelle?). <br> <br>  _@aborruso non mi piace la struttura di questa chiave e il fatto che non si capisca che correlata all'url. Hai in mente un'idea migliore per caso?_                                                                                          | ![image](https://github.com/user-attachments/assets/31458a37-3e60-4ead-9ed8-c6bcafa0616e)                                                                                                                 |
| `has-header`                 | Booleano            | Va utilizzato solo se `type` è una viz (e quindi `chart`, `map`, `table`, `dashboard`). Indica se la risorsa online prodotta esternamente contiene un'intestazione (header). È utile saperlo per evitare di ripetere lo stesso titolo quando costruiremo una paginetta che contiene l'iframe dell'artifact.                                                                                            | `true`                                                                                                                                                           |
| `thumbnail`                  | URL      | Collegamento o percorso di una miniatura dell'immagine associata all'artifact.                                                                                           | `img/emergenza_idrica.png`                                                                                                                                       |
| `tools`                      | Lista di stringhe              | Elenco degli strumenti utilizzati per creare o gestire l'artifact.                                                                                                       | `- GitHub Pages`<br>`- Datawrapper`                                                                                                                     |
| `created`                    | Data                | Data di creazione dell'artifact.                                                                                                                          | `2024-04-06`                                                                                                                                                     |
| `edited`                     | Data                | Data di ultima modifica dell'artifact.                                                                                                                    | `2024-06-04`                                                                                                                                                     |
| `status`                     | Testo semplice      | Stato dell'artifact per comprendere se è ancora "funzionante". <br> <br> _@aborruso bisogna ancora scegliere quali valori può assumere. dead? alive? ongoing? wip?_                                                                                                      | `dead`                                                                                                                                                        |
| `source` | Lista di oggetti  | Elenco delle fonti associate alla risorsa, includendo titolo e URL | ![image](https://github.com/user-attachments/assets/17eacc67-cea3-4595-8f94-ac1cbfdd0e53) |                                                                                                                       
| `data`                       | Lista di oggetti               | Permette di chiarire quale file di quale dataset è stato utilizzato per generare una determinata viz. <br><br> Contiene le chiavi:<br>- `file` che corrisonde al `name` di una risorsa in un datapackage;<br>- `dataset` che corrisonde al `name` di un artifact di tipo `dataset`.  | ![image](https://github.com/user-attachments/assets/cc03479b-b108-4881-910e-47e569127a59) |
| `blog-post-url`              | URL      | URL di un post sul blog di ODS che è in relazione con l'artifact.  <br><br> _@aboruso forse conviene cancellare questa key e sfruttare `linked-to-artifacts` anche per i post? Di fatto potremmo pensare a un post come a un artifact che non fa parte di questo catalogo perchè gestito dal cms di wp. @gabacode faceva notare che si potrebbe usare anche solo lo slug del blog post_                                                                                                             | `https://opendatasicilia.it/2024/04/24/il-dialogo-con-amap-spa/`                                                                                                  |
| `linked-to-artifacts`         | Lista di stringhe               | Elenco di ID di altri artifact collegati.                                                                                                           | `- project-emergenza-idrica`                                                                                                                                     |
| `contributors`               | Lista di stringhe               | Elenco dei contributori che hanno partecipato alla creazione dell'artifact. <br><br> @aborruso _attualmente è una lista di stringhe ma potrebbe diventare una lista di oggetti (come nei datapackage di frictionless) in cui è possibile individuare il ruolo di ciascun contributor. Che dici? Utilizziamo stessa struttura di frictionless o manteniamo questa lista più semplice?_                                                                                                | `- Ciro Spataro`<br>`- Andrea Borruso`                                                                                                                              |
| `repository`                 | Testo semplice      | URL o percorso del repository GitHub o altro sistema di controllo versione associato al progetto o alla risorsa.                                                         | `opendatasicilia/emergenza-idrica-sicilia`                                                                                                                       |

> [!TIP]
> @pcmasuzzo mi ha fatto notare che si potrebbe creare una community zenodo per ods in cui rilasciare i dataset che pubblichiamo su github. In questo caso, bisognerebbe aggiungere il doi al datapackage che descrive il dataset usando la chiave `id` ([qui documentazione frictionless](https://datapackage.org/standard/data-package/#id)) 

---

## Esempio di (una porzione) del catalogo YAML

Qui un file yaml che è aderente alle specifiche sopra indicate. Quando le modificheremo sulla base delle valutazioni di @aborruso, sarà necessario aggiornare il codice di questo catalogo di test e poi potrà essere sfruttato da @gabacode per provare a generare le prime pagine.

```yaml

# Il catalogo della community Open Data Sicilia

### artifact-template ###
# - name: 
#   title:
#   description: |
#     
#   type: 
#   url:
#   iframe: |
#    
#   resource:
#     - name:
#       position:
#   has-header:
#   thumbnail:
#   tools:
#     - 
#   created:
#   edited:
#   status:
#   source:
#     - title:
#       url:
#   data:
#     - file:
#       dataset:
#     - url:
#   blog-post-url:
#   linked-to-artifacts:
#     - 
#   contributors:
#     - 
### fine-artifact-template ###

- name: project-emergenza-idrica
  title: Emergenza idrica
  type: project
  status: ongoing
  created: 2024-04-06
  description: Emergenza idrica in Sicilia. Raccogliamo dati, dashboard e avvisi dei gestori idrici. Facciamo un po' di advocacy.
  repository: opendatasicilia/emergenza-idrica-sicilia
  linked-to-artifacts:
    - site-emergenza-idrica


- name: site-emergenza-idrica
  title: Emergenza idrica
  type: site
  tools:
    - Material for MkDocs
    - GitHub Pages
  created: 2024-04-06
  url: https://opendatasicilia.github.io/emergenza-idrica-sicilia/
  repository: opendatasicilia/emergenza-idrica-sicilia
  description: Sito tematico osservatorio sull'emergenza idrica Siciliana. Raccogliamo dati, dashboard e avvisi dei gestori idrici.
  status: alive
  contributors: #fetch from repo?
    - Ciro Spataro
    - Andrea Borruso
    - Giovan Battista Vitrano
    - Salvatore Fiandaca
    - Dennis Angemi
    - Stefano Borzì


- name: dataset-emergenza-idrica-2024
  title: I dati estratti sull'emergenza idrica siciliana del 2024
  url: https://raw.githubusercontent.com/opendatasicilia/emergenza-idrica-sicilia/main/datapackage.yaml
  type: dataset
  resource:
    - name: datapackage
      position: root
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica



- name: map-palermo-distretti-rete-idrica-amap
  title: Palermo, mappa dei distretti gestiti dall'AMAP S.p.A. soggetti a riduzione della pressione idrica
  type: map
  has-header: false
  tools:
    - uMap
  created: 2024-04-24
  url: https://umap.openstreetmap.fr/it/map/distretti-amap-interessati-dalla-riduzione-pressio_1059819#12/38.1374/13.3470
  iframe: |
    <iframe width="100%" height="850px" frameborder="0" allowfullscreen allow="geolocation" src="//umap.openstreetmap.fr/it/map/distretti-amap-interessati-dalla-riduzione-pressio_1059819?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=false&embedControl=false&datalayersControl=false&onLoadPanel=none&captionBar=false&captionMenus=true&locateControl=true&editinosmControl=false&starControl=false"></iframe><p><a href="//umap.openstreetmap.fr/it/map/distretti-amap-interessati-dalla-riduzione-pressio_1059819?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true">Visualizza a schermo intero</a></p>
  description: |
    Mappa dei distretti della rete idrica di Palermo gestita da AMAP. Qui maggiori informazioni https://opendatasicilia.github.io/emergenza-idrica-sicilia/aggiornamenti/2024/04/24/il-dialogo-con-amap-spa/
  blog-post-url: https://opendatasicilia.it/2024/04/24/il-dialogo-con-amap-spa/
  linked-to-artifacts: 
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - Andrea Borruso
    - Giovan Battista Vitrano


- name: map-comuni-riduzione-fornitura-idrica-042024
  title: Sicilia | Comuni con riduzione della fornitura idrica
  has-header: true
  url: https://www.datawrapper.de/_/ZqqSS/
  iframe: |
   <iframe title="Sicilia | Comuni con riduzione della fornitura idrica" aria-label="Mappa" id="datawrapper-chart-ZqqSS" src="https://datawrapper.dwcdn.net/ZqqSS/16/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="420" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
  type: map
  tools:
    - Datawrapper
  created:
  edited: 2024-04-05
  description:
  source: 
    - title: Regione Siciliana
      url: https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/stato-emergenza-crisi-idrica
  blog-post-url: 
  data:
    - file: sicilia_riduzione_idrica_20240405
      dataset: dataset-emergenza-idrica-2024
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
    - table-comuni-riduzione-fornitura-idrica-042024
    - dataset-emergenza-idrica-2024
  contributors:
    - Giovan Battista Vitrano


- name: table-comuni-riduzione-fornitura-idrica-042024
  title: Sicilia | Comuni con riduzione della fornitura idrica
  type: table
  has-header: true
  tools:
    - Datawrapper
  url: https://www.datawrapper.de/_/Q3P9J/
  iframe: |
   <iframe title="Sicilia | Comuni con riduzione della fornitura idrica" aria-label="Tabella" id="datawrapper-chart-Q3P9J" src="https://datawrapper.dwcdn.net/Q3P9J/15/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="1411" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
  edited: 2024-04-05
  source:
    - title: Presidenza della Regione/Autorità di Bacino del Distretto Idrografico della Sicilia
      url: https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/stato-emergenza-crisi-idrica
  data:
    - file: sicilia_riduzione_idrica_20240405
      dataset: dataset-emergenza-idrica-2024
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
    - map-comuni-riduzione-fornitura-idrica-042024
    - dataset-emergenza-idrica-2024
  contributors:
    - Giovan Battista Vitrano


- name: map-comuni-ordinanze-risparmio-idrico
  title: Sicilia | Comuni che hanno emanato ordinanze funzionali al risparmio idrico potabile
  has-header: true
  url: https://www.datawrapper.de/_/8jG3R/
  iframe: |
   <iframe title="Sicilia | Comuni che hanno emanato ordinanze funzionali al risparmio idrico potabile" aria-label="Mappa" id="datawrapper-chart-8jG3R" src="https://datawrapper.dwcdn.net/8jG3R/7/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="493" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
  type: map
  tools:
    - Datawrapper
  created:
  edited: 2024-06-07
  description: 
  source: 
    - title: Ufficio stampa della Regione Siciliana
      url: https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/stato-emergenza-crisi-idrica
  linked-to-artifacts:
    - site-emergenza-idrica
    - project-emergenza-idrica
  contributors:
    - Giovan Battista Vitrano


- name: dashboard-dighe-volumi
  title: Mappa delle dighe e serie storica sulle riserve idriche (2010 - 2024)
  type: dashboard
  tools:
    - Tableau Public
  url: https://public.tableau.com/app/profile/gbvitrano/viz/Sicilia2024Dighevolumiinvasi/Dashboard
  iframe: |
    <div class='tableauPlaceholder' id='viz1722132148038' style='position: relative'><noscript><a href='#'><img alt='Dashboard ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Si&#47;Sicilia2024Dighevolumiinvasi&#47;Dashboard&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Sicilia2024Dighevolumiinvasi&#47;Dashboard' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Si&#47;Sicilia2024Dighevolumiinvasi&#47;Dashboard&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='it-IT' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1722132148038');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='1077px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
  has-header: false
  source:
    - title: Regione Siciliana
      url: https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia
  created: 2024-04-10
  edited: 2024-06-04
  data:
    - file: sicilia_dighe_volumi
      dataset: dataset-emergenza-idrica-2024
  linked-to-artifacts:
    - site-emergenza-idrica
    - project-emergenza-idrica
    - dataset-emergenza-idrica-2024
  contributors:
    - Giovan Battista Vitrano


- name: map-principali-risorse-idriche-sicilia
  title: Le principali risorse idriche della Sicilia
  url: https://umap.openstreetmap.fr/it/map/sicilia-principali-risorse-idriche_1051183?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true#8/37.528/14.134
  iframe: |
   <iframe width="100%" height="600px" frameborder="0" allowfullscreen allow="geolocation" src="//umap.openstreetmap.fr/it/map/sicilia-principali-risorse-idriche_1051183?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true"></iframe><p><a href="//umap.openstreetmap.fr/it/map/sicilia-principali-risorse-idriche_1051183?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true">Visualizza a schermo intero</a></p>
  type: map
  has-header: false
  tools:
    - uMap
    - OpenStreetMap
    - Google Maps
  source:
    - title: Regione Siciliana
      url: https://www.regione.sicilia.it/la-regione-informa/pubblicati-dati-invasi-mese-gennaio-2024
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - Giovan Battista Vitrano


- name: map-grandi-dighe-italiane
  title: Cartografia delle grandi dighe
  url: https://dgdighe.mit.gov.it/CartografiaDighe/mappa-dighe
  iframe: |
    <iframe title="Cartografia delle grandi dighe" aria-label="Mappa" src="https://dgdighe.mit.gov.it/CartografiaDighe/mappa-dighe" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="950" data-external="1"></iframe>
  type: map
  has-header: false
  source:
    - title: Ministero delle Infrastrutture e dei Trasporti - Direzione generale per le dighe le infrastrutture idriche
      url: https://dgdighe.mit.gov.it/categoria/articolo/_cartografie_e_dati/_cartografie/cartografia_dighe
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - MIT


- name: table-utd-palermo-registro-grandi-dighe
  title: UTD Palermo - Registro delle grandi dighe
  url: https://www.datawrapper.de/_/xhTbd/
  iframe: |
   <iframe title="UTD Palermo - Registro delle grandi dighe" aria-label="Tabella" id="datawrapper-chart-xhTbd" src="https://datawrapper.dwcdn.net/xhTbd/2/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="1387" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
  type: table
  has-header: true
  tools:
    - Datawrapper
  description: Elenco delle dighe di competenza dell'ufficio tecnico per le dighe di Palermo al 31/12/2023.
  source:
    - title: Ministero delle Infrastrutture e dei Trasporti
      url: https://dgdighe.mit.gov.it/categoria/articolo/_cartografie_e_dati/_dighe_di_competenza/UTDPA
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - Giovan Battista Vitrano


- name: table-regalbuto-rete-idrica-turnazione-0724
  title: Turnazione erogazione idrica Regalbuto
  url: https://www.datawrapper.de/_/TeN8s/
  iframe: |
   <iframe title="Turnazione erogazione idrica Regalbuto" aria-label="Tabella" id="datawrapper-chart-TeN8s" src="https://datawrapper.dwcdn.net/TeN8s/6/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="775" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();</script>
  type: table
  has-header: true
  tools:
    - Datawrapper
  description: Il 22 luglio 2024 il gestore AcquaEnna ha comunicato al Comune di Regalbuto che l'erogazione idrica avverrà a giorni alterni secondo questo schema diffuso dal Sindaco Longo. La community Open Data Sicilia (grazie a Giovan Battista Vitrano) ha georeferenziato l'immagine, estratto i poligoni ed effettuato intersezioni con stradario OpenStreetMap. Consulta la mappa interattiva oppure usa la barra di ricerca di questa tabella!
  source:
    - title: Comune di Regalbuto
      url: https://www.facebook.com/photo/?fbid=3769636563307716&set=a.1999750763629647
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - Dennis Angemi
    - Giovan Battista Vitrano


- name: dashboard-regalbuto-turnazione-idrica-0724
  title: Regalbuto, rete idrica ed erogazioni
  url: https://public.tableau.com/app/profile/gbvitrano/viz/Regalbuto/Turno_erogazione_idrica_Regalbuto
  iframe: |
   <div class='tableauPlaceholder' id='viz1721886783846' style='position: relative'><noscript><a href='#'><img alt='Turno_erogazione_idrica_Regalbuto ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Re&#47;Regalbuto&#47;Turno_erogazione_idrica_Regalbuto&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Regalbuto&#47;Turno_erogazione_idrica_Regalbuto' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Re&#47;Regalbuto&#47;Turno_erogazione_idrica_Regalbuto&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='it-IT' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1721886783846');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='650px';vizElement.style.height='1027px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='650px';vizElement.style.height='1027px';} else { vizElement.style.width='100%';vizElement.style.height='1027px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
  type: dashboard
  has-header: true
  tools:
    - Tableau Public
    - OpenStreetMap
    - Bing
    - Here
  created: 2024-07-24
  edited: 2024-07-25
  source:
    - title: Comune di Regalbuto
      url: https://www.facebook.com/photo/?fbid=3769636563307716&set=a.1999750763629647
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
  contributors:
    - Giovan Battista Vitrano
```

**Comment by gabacode** [comment]
Ho buttato giu una struttura basilare che riflette gli yaml forniti via #79 
Su https://dev.opendatasicilia.it si puo' vedere la nuova sezione "Catalogo" con i dati alimentati dagli yaml presenti nella cartella `/catalog` della root del repo.

@dennisangemi @aborruso

**Comment by dennisangemi** [comment]
🥹🥹🥹 grazie @gabacode <3 non so perché ma sta cosa mi fa emozionare haha

🚀🚀🚀

**Comment by dennisangemi** [comment]
Ciao @gabacode, grazie! Stavo guardando randomicamente un paio di cose e ho notato che la mia prima versione dello schema del catalogo può essere migliorata (ovviamente). 

In particolare, la sezione dedicata ai dataset attualmente è popolata in questo modo:

```yaml
- name: dataset-emergenza-idrica-2024
  title: I dati estratti sull'emergenza idrica siciliana del 2024
  url: https://raw.githubusercontent.com/opendatasicilia/emergenza-idrica-sicilia/main/datapackage.yaml
  type: dataset
  resource:
    - name: datapackage
      position: root
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
```

La nuova versione invece potrebbe avere la chiave dell'url spostata dentro resource:

```yaml
- name: dataset-emergenza-idrica-2024
  title: I dati estratti sull'emergenza idrica siciliana del 2024
  type: dataset
  resource:
    - name: datapackage
      position: root
      url: https://raw.githubusercontent.com/opendatasicilia/emergenza-idrica-sicilia/main/datapackage.yaml
  linked-to-artifacts:
    - project-emergenza-idrica
    - site-emergenza-idrica
```

Così, forse, la struttura è un po' più chiara.

Grazie sempre
